version: '3.8'

services:
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - 5432:5432

  backend:
      container_name: hakaton-back
      build: .
      links:
        - db:db
      depends_on:
        - db
      expose:
        - "8080"
      ports:
        - "8080:8080"
      restart: always

