spring:
  freemarker:
    check-template-location: false
  servlet:
    multipart:
      enabled: true
  datasource:
    name: primaryDS
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    url: ${DATABASE_URL:jdbc:postgresql://dpg-chpnbke7avjb90npfabg-a.frankfurt-postgres.render.com:5432/hakaton}
    username: ${DATABASE_USER:hakaton}
    password: ${DATABASE_PASSWORD:xoW5rvijy7VnvbRPlUuWLGzDZLINHCEI}
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    drop-first: false
    contexts: local
  cache:
    type: None
  jpa:
    properties:
      hibernate:
        synonyms: true
        default_batch_fetch_size: 100
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        batch_fetch_style: DYNAMIC
        criteria:
          literal_handling_mode: BIND
        connection:
          includeSynonyms: true
          charSet: UTF-8
        jdbc:
          batch_size: 100
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
    exclude[2]: org.springframework.boot.actuate.autoconfigure.metrics.web.tomcat.TomcatMetricsAutoConfiguration
    exclude[3]: org.springframework.boot.actuate.autoconfigure.metrics.web.servlet.WebMvcMetricsAutoConfiguration
    exclude[4]: org.springframework.boot.actuate.autoconfigure.metrics.export.simple.SimpleMetricsExportAutoConfiguration
    management:
      metrics:
        enable:
          tomcat: false
          jvm: false
          process: false
          hikaricp: false
          system: false
          jdbc: false
          http: false
          logback: true